/////////////////////////////////////////////////////////
//   Portuguese (BR) Translation by  HELL/AbstractGR   //
/////////////////////////////////////////////////////////
DIO_LANG.br = {
    Notification: {
        //A: "",
        //B: "",
        //C: "",
    },
    link: {
        ///update
        //update: "",
        //update_direct: "",
        ///donate:
        //Donate: "",
        ///autre
        //Update: "",
        //contact: "",
        forum: "https://br.forum.grepolis.com/index.php?threads/script-dio-tools-david1327.23781/",
        //link_troupes: "",
        //link_utile: "",
        ///help
        //available_units: "",
        //UnitComparison: "",
        //MessageExport: "",
        //Translations: "",
    },
    Settings: {
        Settings: "",
        dsc: "DIO-Tools oferece, entre outras coisas, algumas telas, uma caixa de smiley, opções de comércio e algumas alterações no layout.",
        act: "Ativar/desativar recursos do conjunto de ferramentas:",
        prv: "Pré-visualização de vários recursos:",

        version_old: "Versão não está atualizada",
        version_new: "Versão está atualizada",
        version_dev: "Versão do desenvolvedor",

        version_update: "Atualização",
        Donate: "Doar",

        //forum: "",
        Update: "Atualizar",
        Feature: "Nova funcionalidade",
        Feature2: "Nova versão",
        Learn_more: "Saber mais",

        cat_units: "Unidades",
        cat_icons: "Cidades",
        cat_forum: "Forum",
        cat_trade: "Comércio",
        cat_wonders: "Maravilhas do Mundo",
        cat_layout: "Layout",
        cat_other: "Outros",
        cat_Premium: "Premium",
        cat_Quack: "Quack",

        install: "Instalar",
        reminder: "Lembrar mais tarde",
        Available: "Nova versão disponível",
        reqreload: "Atualização requerida",
        reload: "Atualizar",

        Comp_GRCT: "As seguintes funções não são compatíveis com GRCT",
        Non_compatible: "Não compatível, ative nas definições de",
    },
    Options: {
        Options: "",
        // bir: ["Contador de Birremes", "Conta as biremes da cidade na cidade"],
        ava: ["Visão geral da unidade", "Indica as unidades de todas as cidades"],
        ava2: ["Número do oceano", "Unidade de extensão"],
        sml: ["Smilies", "Estende o bbcode com uma caixa de smiley"],
        str: ["Força das Tropas", "Adiciona quadros de força das tropas em diversas áreas"],
        tra: ["Capacidade de Transporte", "Mostra a capacidade de transporte ocupado e disponível no menu de unidades"],
        per: ["Percentual de comércio", "Estende-se a janela de comércio com um percentual de comércio"],
        rec: ["Comércio para recrutamento", "Estende-se a janela de comércio com um comércio de recrutamento"],
        cnt: ["Conquistas", "Conta os ataques/apoios na janela de conquista"],
        way: ["Velocidade da tropa", "Displays mostram a possivél velocidade de tropa na janela de ataque/suporte"],
        sim: ["Simulador", "Adaptação do layout simulador & exposição permanente da caixa poderes estendida"],
        act: ["Ativar caixas suspensas de comércio e ataque", "Melhorias da exibição de caixas de comércio e recrutamento (com memória de posição)"],
        pop: ["Caixa de favores divino", "Altera a caixa de favores divino por um novo layout"],
        tsk: ["Barra de tarefas", "Aumenta a barra de tarefas"],
        rew: ["Recompensa diária", "Minimiza a janela recompensa diária no inicio"],
        bbc: ["Pedido de Apoio", "Estende a barra de bbcode com uma forma de Pedido de Apoio Automática"],
        com: ["Comparação de Unidades", "Adiciona tabelas de comparação de unidade"],
        tic: ["Ícones nas Cidades", "Cada cidade recebe um ícone para o tipo de tropas na cidade (detecção automática) ", " Ícones adicionais estão disponíveis para seleção manual"],
        tic2: ["Detecção automática", ""],
        til: ["Lista das Cidades", "Adiciona os ícones da cidade na lista de cidades"],
        tim: ["Mapa", "Mostra os ícones das cidades no mapa estratégico"],
        tiw: ["Pop-up de ícone", ""],
        wwc: ["Calculadora de WW", "Cálculo compartilhado & contador de recursos + botões anterior e próxima maravilhas do mundo (atualmente não desactivável!)"],
        wwr: ["Classificação", "Classificação das maravilha do mundo redesenhadas"],
        wwi: ["Icones", 'Adiciona ícones nas maravilha do mundo no mapa estratégico'],
        con: ["Menu de Contexto", 'Troca da "Selecione cidade" e "Visão Geral da Cidade" no menu de contexto'],
        sen: ["Unidades Enviadas", 'Shows sent units in the attack/support window'],
        tov: ["Visão da Cidade", 'Substitui o novo panorama da cidade, com o estilo da janela antiga'],
        scr: ["Roda do Mouse", 'Você pode alterar os pontos de vista com a roda do mouse'],
        Scr: ["Barra de deslocamento", "Altera a cor da barra de deslocamento"],
        tow: ["Cidade BBCode", "Adiciona o BBCode da cidade à aba da cidade"],
        Fdm: ["Selecione e apague várias mensagens", "Você pode excluir mais de uma mensagem. Função Quack"],
        Sel: ["Adicionar (Sem sobrecarga / Excluir)", "Melhoria de novas ferramentas na janela de ataque e suporte. Função Quack"],
        Cul: ["Visão geral da cultura (Administrador)", "Adicionar um contador para a festa na visualização de cultura. Função Quack"],
        Hot: ["Atalhos do teclado para Windows", "Isso muda sua vida"],
        Isl: ["Visualização da ilha", "Aumentar a altura da lista de cidades e vilas. Função Quack"],
        Ish: ["Visão geral das aldeias bárbaras (Capitão)", "Ocultar automaticamente a cidade. Função Quack"],
        Hio: ["Visão geral das Grutas (Administrador)", "Permitir o filtro de cidades"],
        Hid: ["Gruta", "Digita prata acima 15000 automaticamente no campo. Função Quack"],
        Tol: ["Lista de cidades em BB-Code", "Copiar e colar. Função Quack"],
        Cib: ["Botão de vista da cidade", "Adicionar um botão para abrir a vista da cidade ao menu lateral. Função Quack"],
        Ciw: ["Vista da cidade", "Mostrar vista para a cidade em uma janela. Função Quack"],
        Tti: ["Envie recursos para festivais", "Clique nele e só será enviado para um festival. Função Quack"],
        Mse: ["Mensagens do Código BB", "Converter mensagens em Código BB. Função Quack"],
        Rep: ["Relatórios", "Adicionando um filtro de cores. Função Quack"],
        BBt: ["Botão de BBCode nas informações do jogador", "Adiciona um botão de BBCode (jogador e aliança)"],
        Rtt: ["Remoção das dicas da unidade", ""],
        Cup: ["Avanço da Cultura (Administrador)", "Alterada a apresentação da barra de progresso e adicionada uma barra de progresso para as colheitas. Função de Akiway"],
        Cuo: ["Pontos de Cultura (Administrador)", "Adicione um contador para os Pontos de Cultura. Função Quack"],
        Rct: ["Comércio -> Contador de recursos (Administrador) ", " Uma contagem de todos os recursos em sua cidade"],
        FLASK: ["Não é compatível com a ativação nos parâmetros do FLASK-TOOLS", ""],
        Mole: ["Não é compatível com a ativação nos parâmetros do Mole Hole", ""],
        Cic: ["Vista da Cidade", "O modo de construção com vista para a cidade está selecionado por predefinição"],
        Cuc: ["Filtragem da visão geral da cultura (Administrador)", "Permitir ordenar as cidades"],
        Buc: ["Filtragem da visão geral do edifício (Administrador)", "Permitir ordenar as cidades"],
        BBl: ["Lista BBcode", "Gera uma lista em BBcode, ideal para exibir membros de alianças ou as cidades de um jogador"],
        Amm: ["Correio em massa (aliança)", "Adiciona um botão no perfil da aliança para facilitar o envio de mensagens em massa"],
        Onb: ["Número do oceano", "Integra número do oceano à visão da ilha, melhorando a navegação"],
        Idl: ["Jogador Inativo", "Exibe jogadores inativos para uma gestão mais eficaz. Desenvolvido por GREPODATA"],
        Saw: ["Salvar muralha", "Permite salvar as tropas na muralha"],
        Att: ["Alarme de ataque", "Receba alertas instantâneos quando estiver sob ataque, reforçando sua segurança"],
        Com: ["Coloração de mensagens", "Aplica uma cor às mensagens com base na sua origem (aliança, inimigo, pacto)."],
        
        //Comp_GRCT: ["undefined", "undefined"],
        //Non_compatible: ["undefined", "undefined"],
        err: ["Enviar automaticamente relatórios de erros", "Se você ativar essa opção, você pode ajudar a identificar erros."],
        //her: ["Conquista Thracian", "Redução de tamanho do mapa da conquista Thracian."],
    },
    Movement: {
        movement: "Movimento",
        off: "Ataque a caminho",
        offs: "Ataques a caminho",
        def: "Apoio a caminho",
        defs: "Apoios a caminho",
    },
    Town_icons: {
        Town_icons: "Ícones das cidades",
        LandOff: "Ofensiva terrestre",
        LandDef: "Defensiva terrestre",
        NavyOff: "Ofensiva naval",
        NavyDef: "Defensiva naval",
        FlyOff: "Ofensiva aérea",
        FlyDef: "Defensiva aérea",
        Out: "Fora",
        Emp: "Vazia",
    },
    Color: {
        Color: "Cor",
        Blue: 'Azul',
        Red: 'Vermelho',
        Green: 'Verde',
        Pink: 'Rosa',
        White: "Branco",
    },
    labels: {
        labels: "Etiquetas",
        uni: "Visão Geral da unidade",
        total: "Global",
        available: "Disponível",
        outer: "Fora",
        con: "Selecionar cidade",
        /// Smileys
        std: "Padrão",
        gre: "Grepo",
        nat: "Natural",
        ppl: "Popular",
        Par: "Festa",
        oth: "Outros",
        hal: "Halloween",
        xma: "Natal",
        eas: "Páscoa",
        lov: "Amor",
        /// Defense form
        ttl: "Pedido de Apoio",
        inf: "Informação da cidade:",
        dev: "Desvio",
        det: "Unidades Detalhadas",
        prm: "Bônus Premium",
        sil: "Prata na Gruta",
        mov: "Movimentação de Tropas:",
        /// WW
        leg: "WW Maravilhas",
        stg: "Level",
        tot: "Total",
        /// Simulator
        str: "Força das Unidades",
        los: "Perdas",
        mod: "Sem modificador de influência",
        /// Comparison box
        dsc: "Comparação de unidades",
        hck: "Impacto",
        prc: "Corte",
        dst: "Arremesso",
        sea: "Naval",
        att: "Ofensivo",
        def: "Defensivo",
        spd: "Velocidade",
        bty: "Saque (recursos)",
        cap: "Capacidade de trasporte",
        res: "Custo (recursos)",
        fav: "Favor",
        tim: "Tempo de recrutamento (s)",
        /// Trade
        rat: "Proporção de recursos de um tipo de unidade",
        shr: "Compartilhamento da capacidade de armazenamento da cidade-alvo.",
        per: "Percentual de comércio",
        /// Sent units box
        lab: "Unidades enviadas",
        rec: "Recursos",
        improved_movement: "Movimento de tropas melhorado",
        Tran: "Traduções",
        donat: "Doações",
        Happy: "Feliz Ano Novo!",
        Merry: "Ho Ho Ho Feliz Natal!",
        tow: "Cidade BBCode",
        loc: "",
        ingame_name: "Como este projeto exige muito trabalho e pode consumir bastante tempo, sou sempre muito grato por qualquer tipo de apoio. Por isso, gostaria de agradecer a todos que contribuíram para este projeto, seja por meio de doações, conhecimento, criatividade, relatórios de erros ou simplesmente com algumas palavras de incentivo.",
        raf: "Ao confirmar a página será atualizada",
        con: "",
        Volume: "",
    },
    tutoriel: {
        tuto: "Informações úteis",
        reme: ["Agradeço a todos que contribuíram para o desenvolvimento de DIO-TOOLS-David1327", ""],

        Trou: "O que você precisa saber sobre as tropas do Grepolis - pontos fortes/fracos das unidades",
        util: "Uma variedade de ferramentas para Grepolis: estatísticas, mapas, ferramentas, scripts, fórum... estão todas listadas aqui.",
    },
    Quack: {
        // delete multiple forum
        delete_mul: "Excluir várias mensagens",
        delete_sure: "Você realmente quer apagar essas mensagens?",
        no_selection: "Nenhuma mensagem selecionada",
        mark_All: "Marcar todos",
        //select unit shelper
        no_overload: 'Sem sobrecarga',
        delete: 'Excluir',
        //culture Overview
        cityfestivals: 'Festival Urbano',
        olympicgames: 'Jogos Olímpicos',
        triumph: 'Desfile da Vitória',
        theater: 'Peças de Teatro'
    },
    hotkeys: {
        hotkeys: 'Teclas de atalho',
        Senate: 'Senado',
        city_select: 'Seleção Cidade',
        last_city: 'Última cidade',
        next_city: 'Próxima cidade',
        jump_city: 'Ir para a cidade atual',
        administrator: 'Administrador',
        captain: 'Capitão',
        trade_ov: 'Troca',
        command_ov: 'Comandos',
        recruitment_ov: 'Recrutamento',
        troop_ov: 'Visão geral das tropasa',
        troops_outside: 'Tropas no exterior',
        building_ov: 'Edifícios',
        culture_ov: 'Cultura',
        gods_ov: 'Deuses',
        cave_ov: 'Grutas',
        city_groups_ov: 'Grupos de cidades',
        city_list: 'Lista de cidades',
        attack_planner: 'Planejador de ataques',
        farming_villages: 'Aldeias bárbaras',
        menu: 'Menu',
        city_view: 'Vista da cidade',
        messages: 'Mensagens',
        reports: 'Relatórios',
        alliance: 'Aliança',
        alliance_forum: 'Fórum da aliança',
        settings: 'Configurações',
        profile: 'Perfil',
        ranking: "Classificação",
        notes: 'Notas',
        chat: 'Chat',
        council: 'Conselho de Heróis',
        Configure: "Configurar atalhos",
    },
    messages: {
        messages: "Mensagens",
        ghosttown: "Cidade-fantasma",
        no_cities: "Nenhuma cidade nesta ilha",
        all: "Tudo",
        export: "Converter mensagem em BB-Code",
        Tol: "Copiar e colar (Função Quack)",
        copy: "Copiar",
        bbmessages: "Mensagens do BB-Code",
        copybb: "BBCode foi copiado",
        écrit: "escreveu o seguinte:",
        cli: "A mensagem não foi copiada",
    },
    caves: {
        caves: "Gruta",
        stored_silver: 'Moedas de prata armazenadss',
        silver_to_store: 'Moedas de prata armazenáveis',
        name: 'Nome',
        wood: 'Madeira',
        stone: 'Pedra',
        silver: 'Moedas de prata',
        search_for: "Pesquisar por",
    },
    grepo_mainmenu: {
        grepo_mainmenu: "Menu principal do Grepo",
        city_view: 'Vista da cidade',
        island_view: 'Vista Ilha'
    },
    transport_calc: {
        transport_calc: "Capacidade de transporte",
        recruits: "Contagem das unidades na fila de recrutamento",
        slowtrans: "Contar navios de transporte lentos",
        fasttrans: "Contar navios de transporte rápidos",
        Lack: "Falta",
        Still: "Ainda",
        pop: "população disponível. Para o",
        Optipop: "População ideal para",
        army: "Você não tem um exército.",
    },
    reports: {
        reports: "Relatórios",
        choose_folder: "Escolher pasta",
        enacted: "lançou",
        conquered: "conquistou",
        spying: "espionando",
        spy: "Espião",
        support: "apoio",
        support2: "não é possível apoiar",
        supporting: "estacionadas",
        attacking: "atacando",
        farming_village: "aldeia bárbara",
        gold: "Você recebeu",
        Quests: "Missões",
        Reservations: "Sua reserva para",
    },
    translations: {
        translations: '',
        info: 'Info',
        trans: "Tradução para o idioma",
        translations: 'Traduções',
        trans_sure: 'Tem certeza de que sua tradução está pronta para ser gerada?',
        trans_success: 'A tradução foi enviada com sucesso',
        trans_fail: 'A tradução não pôde ser enviada',
        trans_infotext1: 'Tradução disponível',
        trans_infotext2: 'Para modificar ou criar um novo idioma, escolha o idioma no menu suspenso',
        trans_infotext3: 'Quando um texto contém tags HTML (portanto, tudo que está entre <> colchetes) eu peço que você os mantenha onde os encontrou',
        trans_infotext4: 'Quando você terminar de traduzir, pressione',
        trans_infotext5: 'Para poder adicionar você aos créditos, seu apelido será gerado',
        trans_infotext6: 'Copie a mensagem gerada e cole-a em um comentário',
        please_note: 'Por favor, note',
        credits: 'Créditos',
        no_translation: 'Nenhuma tradução encontrada',
        choose_lang: 'Escolha o idioma',
        add_lang: 'Adicionar um novo idioma',
        language: 'Idioma',
        enter_lang_name: 'Por favor, digite um nome de idioma',
        send: 'Gerar mensagem',
        name: 'Nome',
        add_edit: "Adicionar / editar",
    },
    wall: {
        wall: "Muralha",
        wallnotsaved: "Muralha não foi salva",
        wallsaved: "Muralha foi salva",
        msghuman: "Informação salva com sucesso",
        erreur: "Ocorreu um erro ao salvar",
        wantdeletecurrent: "Quer apagar o registo corrente da muralha?",
        deletecurrent: "Apagar o registo corrente",
        listsaved: "Muralha salva no dia",
        liststate: "Condição da muralha no dia",
        nosaved: "Sem backup",
        Auto: "Modo automático",
    },
    Radar: {
        Radar: "Pesquisar cidades",
        find: "Pesquisar",
        maxunittime: "Tempo máximo",
        townname: "Cidade",
        unittime: "Tempo",
        townowner: "Dono",
        townreserved: "Reserva",
        townpoints: "Pontos mínima da cidade",
        btnsavedefault: "Salvar valores como padrão",
        all: "Qualquer cidade",
        showcities: "Pesquisar cidades",
    },
    TSL: {
        TSL: "Lista de cidades ordenadas",
        tooltip: "Mostrar cidade ordenada",
    },
    AO: {
        AO: "Visão geral da academia",
    },
    ABH: {
        ABH: "Construtor de exércitos",
        unitframe: "selecione a sua unidade",
        description1: "Nesta cidade, você tem [population] de população livre",
        description2: "Que é o suficiente para recrutar [max_units]",
        description3: "Você [yesno] tem a pesquisa [research] concluída.",
        description4: "Você pode colocar no máximo [max_queue] unidades na fila",
        target: "escolha seu objetivo de construção",
        package: "pacote de recursos por remessa (unidades)",
        btnsave: "Salvar configurações",
        tooltipok: "clique para selecionar a unidade padrão para a qual você enviará os recursos",
        tooltipnotok: "a unidade não foi pesquisada",
        hasresearch: "TEM",
        noresearch: "NÃO TEM",
        settingsaved: "As configurações para [city] foram salvas",
        btnreset: "resetar",
        resleft: "recursos restantes para enviar",
        imgtooltip: "clique para preencher os recursos",
    },
    Stats: {
        player: "Estatísticas do jogador",
        ally: "Estatísticas da aliança",
        town: "Estatísticas da cidade",
        inactive: "Inativo",
        chkinactive: "Mostrar jogadores inativos",
    },
    buttons: {
        sav: "Salvar", ins: "Inserir", res: "Resetar"
    }
};
DIO_LANG.pt = DIO_LANG.br;